# can also admin admin mongo db from Robo 3T: https://robomongo.org/

version: "3.8"
services: 
  mongo:
    image: mongo:4.2-bionic
    container_name: mongodb
    restart: unless-stopped
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - mongo-db:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - db

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}      
    networks:
      - db

networks:
  db:

volumes:
  mongo-db: