http:
  routers:
    my-router:
      rule: Host(`canary.docker.localhost`)
      service: canary
  services:
    canary:
      weighted:
        services:
          - name: appv1
            weight: 3
          - name: appv2
            weight: 1
    appv1:
      loadBalancer:
        servers:
          - url: 'http://docker.for.mac.localhost:8180'
    appv2:
      loadBalancer:
        servers:
          - url: 'http://docker.for.mac.localhost:8181'