[http.routers]
  [http.routers.my-router]
    rule = "Host(`canary.docker.localhost`)"
    service = "canary"

[http.services]
  [http.services.canary]
    [[http.services.canary.weighted.services]]
      name = "appv1"
      weight = 3
    [[http.services.canary.weighted.services]]
      name = "appv2"
      weight = 1
  [http.services.appv1]
    [http.services.appv1.loadBalancer]
      [[http.services.appv1.loadBalancer.servers]]
        url = "http://docker.for.mac.localhost:8180"
  [http.services.appv2]
    [http.services.appv2.loadBalancer]
      [[http.services.appv2.loadBalancer.servers]]
        url = "http://docker.for.mac.localhost:8181"