version: "3.8"

services: 
  nestjs:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    env_file: .env
    volumes:
      - .:/node/app
      - /node/app/node_modules  # this hides the node_modules directory that exists in the host system
    ports:
      - ${PORT_API}:${PORT_API}
      - 9229:9229
    networks:
      - back-end

networks:
  back-end:


