version: "3.8"

services: 
  nestjs:
    build:
      context: .
      target: dev
      # target: prod
    # command: npm run start:debug
    env_file: .env
    volumes:
      - .:/node/app:delegated
      - /node/app/node_modules  # this hides the node_modules directory that exists in the host system
    ports:
      - ${PORT_API}:${PORT_API}
      - 9229:9229
    networks:
      - backend

networks:
  backend:


