version: "3.8"

services:
  jupyter:
    container_name: jupyter
    build: 
      context: .
    ports:
      - 8888:8888
    volumes:
      - jupyter-data:/home/jupyter
    networks:
      - jupyter

networks:
  jupyter:

volumes:
  jupyter-data:        
