version: "3.8"

services:
  redis:
    image: redis:6.0
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis: